### ISSUE TITLE
エロマンガ先生の紗霧を追加してほしい

### ISSUE THREAD

**Issue by ghost** [ngineerxiv/dark-bot#261]
キャラクタ追加の方法がわからなかったのでここに書きます

input
```
dark エロマンガ先生
```

(日本語いけたっけ？)

output(ランダム)
```
:sagiri: そ…そんな恥ずかしい名前の人、知らない////
:sagiri: 何で私にかまうの？放っておけばいいのに！
:sagiri: あんなやつに絶対絶対負けるもんか！
```

よろしくお願いします

**Comment by ara-ta3** [comment]
hubot-characterの設定だけで行けそうな気がする

**Comment by ara-ta3** [comment]
![LGTM](https://user-images.githubusercontent.com/2089153/27859114-ae848216-61b2-11e7-814d-eb239fbe1a9a.png)

**Comment by ghost** [comment]
thx!!
